export * from "./RegisterTemplate"
export * from "./LoginTemplate"
export * from "./HomeTemplate"
export * from "./LichChieuTemplate"
export * from "./BookingTemplate"
export * from "./DetailMovieTemplate"
